executables:
  rscript: "C:/Program Files/R/R-4.5.2/bin/Rscript.exe"


project_root: "../../"

raw_data:
  root: "data_raw"
  gm_flatfiles: "data_raw/gm_flatfiles"
  esm_flatfile: data_raw/gm_flatfiles/ESM_flatfile_SA.csv
  eshm20_attenuation_regions: data_raw/eshm20_attenuation_regions
  eshm20_hmaps: "data_raw/eshm20_hazard_maps"
  eu_shapefile: "data_raw/eu_shapefile"
  rho_models: "data_raw/correlation_models"
  
proc_data:
  root: "data_processed"
  site_selection: "data_processed/01_site_selection"
  site_hazard: "data_processed/03_site_hazard"
  corr_model: "data_processed/02_im_correlation_model"
  gm_databases_for_selection: "data_processed/04_gm_database_for_selection"
  gm_database: "data_processed/04_gm_database_for_selection/ESM-NGAsub_combined.csv"
  gcim_dists: "data_processed/05_gcim_distributions"
  gm_selection: "data_processed/06_gm_selection"

results:
  root: "results"
  site_selection: "results/01_site_selection"
  selected_sites_csv: "results/01_site_selection/sites.csv"
  corr_model: "results/02_im_correlation_model"
  psha: "results/03_psha"
  hazard_curve_plots: "results/03_psha/hc_plots"
  disaggregation_plots: "results/03_psha/disagg_plots"
  AvgSA_03_record_selection: "results/04_record_selection/AvgSA_03"
  AvgSA_06_record_selection: "results/04_record_selection/AvgSA_06"

hazard_models:
  root: "hazard_models"
  eshm20: "hazard_models/eshm20"
  eshm20_site_model: "hazard_models/eshm20/original/eshm20_site_model_v06d.csv"
  eshm20_AvgSA: "hazard_models/eshm20/regional_AvgSA/"
  eshm20_AvgSA_site_model_all: "hazard_models/eshm20/regional_AvgSA/site_model_all_sites.csv"
  eshm20_AvgSA_03_jobfile: "hazard_models/eshm20/regional_AvgSA/config_eshm20_AvgSA_0to3.ini"

scripts: 
  root: "phd_project/scripts"
  residual_partitioning: "phd_project/scripts/WP1_ground_motion_set/residual_partitioning"

models:
  case_study: "casestudy_structures"
  examples: "calculation_examples"

notebooks:
  root: "notebooks"
  figs: "notebooks/figures"

outputs:
  images: "images"
