"""Provenance-aware generation and launching of OpenQuake PSHA calculations.

Historically the WP1 PSHA configs were hand-edited, run with ``oq engine --run``
at the CLI, and the resulting calculation ids were transcribed by hand into the
post-processing notebook. Nothing recorded which config produced which id, or
whether the inputs behind an id had since changed.

This module closes that loop:

- :func:`write_config` renders a job ``.ini`` from a single template, so the only
  things that vary between the six WP1 analyses are the IM period range (via the
  GMM logic tree) and the truncation level.
- :func:`run_or_reuse` launches a calculation only when its inputs have actually
  changed, and records the calc_id in a shared manifest.
- :func:`load_calc_ids` is the accessor the post-processing notebook uses to
  obtain a datastore programmatically instead of by hardcoded integer.

The provenance guard mirrors :mod:`cache_utils` and reuses its primitives, but
cannot use ``load_or_compute`` directly: there the artifact is a pickle this code
owns, whereas here the artifact is a datastore owned by the engine and the thing
worth recording is an integer id in a shared, human-readable manifest.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from string import Template

import numpy as np

from .cache_utils import _diff_inputs, _git_commit, fingerprint

# Verbatim from regional_avgSA/config_eshm20_AvgSA_0to3_psha_all_sites.ini, which
# is known to run. Only description / gsim logic tree / truncation level vary, so
# a generated config must differ from its hand-written ancestor in those lines
# alone. Substitution is $-style because the file is full of {} (the IMTL and
# maximum_distance dicts) that str.format would try to read as fields.
_CONFIG_TEMPLATE = Template("""\
# This model uses all 21 branches of the site model but only a single median
# branch for each GMPE for all teh sites selected for this study.
# The IM is AvgSA[0,$im_upper] wiht 10 evenly spaced periods
#
# GENERATED by notebooks/03_WP1_ground_motion_set/003-psha_setup_and_analyses.ipynb
# Do not edit by hand - edit the template in phd_project/scripts/WP1_ground_motion_set/oq_runner.py

[general]
description = $description
calculation_mode = classical
random_seed = 23

[geometry]

[logic_tree]

[erf]
rupture_mesh_spacing = 5
complex_fault_mesh_spacing = 50
width_of_mfd_bin = 0.1
area_source_discretization = 10.0

pointsource_distance = 75
ps_grid_spacing = 50

[site_params]
reference_vs30_type = measured
reference_vs30_value = 800.0
site_model_file = $site_model_file

reference_depth_to_1pt0km_per_sec = 30.0

[calculation]
source_model_logic_tree_file = $source_model_logic_tree_file
gsim_logic_tree_file = $gsim_logic_tree_file

investigation_time = 1.0

intensity_measure_types_and_levels = {"AvgSA": logscale(0.0005, 3.00, 25)}

truncation_level = $truncation_level
maximum_distance = {'Craton': 400.0,
                    'Subduction Interface': 250.0,
                    'Subduction Inslab': 300.0,
                    'Non-Subduction Deep':500.0,
                    'Volcanic':50.0,
                    'default': 200.0}

[output]
export_dir = output/
mean_hazard_curves = true
hazard_maps = true
quantile_hazard_curves = 0.16 0.50 0.84
poes = 0.019801 0.004988 0.002103 0.001000 0.000404 0.000201 0.000100
""")

SITE_MODEL_FILE = "site_model_casestudy_sites.csv"
SOURCE_MODEL_LOGIC_TREE_FILE = "source_model_logic_tree_eshm20.xml"

GMPE_LOGIC_TREES = {
    "03": "gmpe_logic_tree_AvgSA_0to3_median_branch.xml",
    "06": "gmpe_logic_tree_AvgSA_0to6_median_branch.xml",
}


def analysis_name(im: str, eps: int) -> str:
    """Manifest key for an analysis, e.g. ``AvgSA_03_psha_eps3``."""
    return f"AvgSA_{im}_psha_eps{eps}"


def config_name(im: str, eps: int) -> str:
    """Config filename for an analysis, e.g. ``config_AvgSA_03_psha_eps3.ini``."""
    return f"config_{analysis_name(im, eps)}.ini"


def im_upper(im: str) -> int:
    """Upper period of an AvgSA range key, e.g. ``"03"`` -> ``3``."""
    return int(im[-1])


def analysis_description(im: str, eps: int) -> str:
    """Engine description. Unique per analysis, which is what lets a calc_id be
    recovered from ``oq engine --list-hazard-calculations`` if stdout parsing fails.
    """
    return f"[ESHM20 AvgSA 0 to {im_upper(im)} - all sites - eps{eps}]"


def write_config(
    out_fp: Path,
    *,
    description: str,
    gsim_logic_tree_file: str,
    truncation_level: int,
    im_upper: int,
    site_model_file: str = SITE_MODEL_FILE,
    source_model_logic_tree_file: str = SOURCE_MODEL_LOGIC_TREE_FILE,
) -> Path:
    """Render a job ``.ini``. ``im_upper`` is the upper period of the AvgSA range
    (3 or 6) and is used only in the header comment. Returns the path written.
    """
    out_fp = Path(out_fp)
    text = _CONFIG_TEMPLATE.substitute(
        description=description,
        gsim_logic_tree_file=gsim_logic_tree_file,
        truncation_level=truncation_level,
        im_upper=im_upper,
        site_model_file=site_model_file,
        source_model_logic_tree_file=source_model_logic_tree_file,
    )
    out_fp.parent.mkdir(parents=True, exist_ok=True)
    # Skip a no-op rewrite so the mtime stays stable and the fingerprint below
    # does not churn on every notebook execution.
    if out_fp.is_file() and out_fp.read_text() == text:
        return out_fp
    out_fp.write_text(text)
    return out_fp


# Verbatim from regional_avgSA/config_eshm20_AvgSA_0to3_disagg_all_sites.ini, with
# two deliberate departures, both forced by the engine:
#
#   - intensity_measure_types_and_levels is *absent*. With iml_disagg set, the
#     engine infers the IMTLs from it and raises if both are given
#     (oqvalidation.py:1355-1359).
#   - poes_disagg is replaced by iml_disagg. The two are mutually exclusive
#     (oqvalidation.py:1590), and iml_disagg takes exactly one level per IMT
#     (oqvalidation.py:1352) - hence one config per IML.
#
# num_rlzs_disagg is written explicitly rather than left to default, because 0
# (= all realizations) is load-bearing: the mean disaggregation is only computed
# when Z > 1 (disaggregation.py:285). See write_disagg_config.
_DISAGG_CONFIG_TEMPLATE = Template("""\
# This model uses all 21 branches of the site model but only a single median
# branch for each GMPE for all the sites selected for this study.
# The IM is AvgSA[0,$im_upper] wiht 10 evenly spaced periods
# Disaggregation is carried out for a single target intensity level.
#
# GENERATED by notebooks/03_WP1_ground_motion_set/020-disaggregation.ipynb
# Do not edit by hand - edit the template in phd_project/scripts/WP1_ground_motion_set/oq_runner.py

[general]
description = $description
calculation_mode = disaggregation
random_seed = 23

[geometry]

[logic_tree]

[erf]
rupture_mesh_spacing = 5
complex_fault_mesh_spacing = 50
width_of_mfd_bin = 0.1
area_source_discretization = 10.0
pointsource_distance = 75
ps_grid_spacing = 50

[site_params]
reference_vs30_type = measured
reference_vs30_value = 800.0
site_model_file = $site_model_file

reference_depth_to_1pt0km_per_sec = 30.0

[calculation]
source_model_logic_tree_file = $source_model_logic_tree_file
gsim_logic_tree_file = $gsim_logic_tree_file

investigation_time = 1.0

truncation_level = $truncation_level
maximum_distance = {'Craton': 400.0,
                    'Subduction Interface': 250.0,
                    'Subduction Inslab': 300.0,
                    'Non-Subduction Deep':500.0,
                    'Volcanic':50.0,
                    'default': 200.0}

[disaggregation]
iml_disagg = {"AvgSA": $iml}
disagg_outputs = TRT_Mag_Dist_Eps
max_sites_disagg = 60
num_rlzs_disagg = $num_rlzs_disagg
mag_bin_width = 0.2
distance_bin_width = 10.0
coordinate_bin_width = 5
num_epsilon_bins = 6
""")


def _iml_str(iml: float) -> str:
    """Format an IML for the config and for descriptions.

    The IMLs come out of np.loadtxt as full-precision floats (0.28499999999999998),
    so format them rather than interpolating repr() into the config.
    """
    return f"{float(iml):.6g}"


def disagg_analysis_name(im: str, eps: int, i: int) -> str:
    """Manifest key for a disagg analysis, e.g. ``AvgSA_03_disagg_eps4_iml01``.

    ``i`` is the 1-based index of the IML in the target IML file, so the name is
    stable against the float formatting of the level itself.
    """
    return f"AvgSA_{im}_disagg_eps{eps}_iml{i:02d}"


def disagg_config_name(im: str, eps: int, i: int) -> str:
    """Config filename, e.g. ``config_AvgSA_03_disagg_eps4_iml01.ini``."""
    return f"config_{disagg_analysis_name(im, eps, i)}.ini"


def disagg_description(im: str, eps: int, i: int, iml: float) -> str:
    """Engine description for a disagg analysis.

    The fields that make an analysis unique (im / eps / iml) are deliberately
    front-loaded: _calc_id_from_listing matches against the engine listing's
    *truncated* description column and refuses to guess when the visible text
    cannot tell two analyses apart.
    """
    return (f"[disagg AvgSA{im} eps{eps} iml{i:02d} {_iml_str(iml)}g "
            f"- ESHM20 all sites]")


def write_disagg_config(
    out_fp: Path,
    *,
    description: str,
    gsim_logic_tree_file: str,
    truncation_level: int,
    im_upper: int,
    iml: float,
    num_rlzs_disagg: int = 0,
    site_model_file: str = SITE_MODEL_FILE,
    source_model_logic_tree_file: str = SOURCE_MODEL_LOGIC_TREE_FILE,
) -> Path:
    """Render a disaggregation job ``.ini`` for a single target ``iml``.

    ``num_rlzs_disagg=0`` means *all* realizations, and is the default for a
    reason: the mean disaggregation (``disagg-stats``) is only computed when more
    than one realization is kept (disaggregation.py:285). Setting this to 1 yields
    the realization closest to the mean rather than the mean itself, and produces
    no ``disagg-stats`` output at all.

    Returns the path written.
    """
    out_fp = Path(out_fp)
    text = _DISAGG_CONFIG_TEMPLATE.substitute(
        description=description,
        gsim_logic_tree_file=gsim_logic_tree_file,
        truncation_level=truncation_level,
        im_upper=im_upper,
        iml=_iml_str(iml),
        num_rlzs_disagg=num_rlzs_disagg,
        site_model_file=site_model_file,
        source_model_logic_tree_file=source_model_logic_tree_file,
    )
    out_fp.parent.mkdir(parents=True, exist_ok=True)
    # Skip a no-op rewrite so the mtime stays stable and the fingerprint does not
    # churn on every notebook execution.
    if out_fp.is_file() and out_fp.read_text() == text:
        return out_fp
    out_fp.write_text(text)
    return out_fp


def load_imls(fp: Path):
    """Target disaggregation IMLs, as written by 017 with ``np.savetxt``."""
    return np.atleast_1d(np.loadtxt(Path(fp), delimiter=","))


def _source_models_digest(wp1_dir: Path) -> str:
    """A content hash over the ~37 MB source_models tree.

    This used to be (relpath, size, mtime_ns), on the theory that hashing 37 MB
    of XML on every notebook run was not worth it. That was wrong twice over:

    - mtime is not a property of the *content*. These files are git-tracked, and
      a checkout, merge or stash rewrites every mtime while leaving the bytes
      identical -- so the digest reported "inputs changed" after an unrelated
      branch switch, which would silently re-run hours of completed
      calculations for nothing.
    - the cost it was avoiding is ~0.14 s for the whole tree.

    Hashing the bytes is both correct and cheap, so do that. Streamed in chunks
    to keep the 21.8 MB point-source file off the heap.
    """
    root = Path(wp1_dir) / "source_models"
    h = hashlib.sha256()
    for p in sorted(p for p in root.rglob("*") if p.is_file()):
        h.update(str(p.relative_to(root)).replace("\\", "/").encode())
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
    return h.hexdigest()


def fingerprint_calc(config_fp: Path, wp1_dir: Path) -> dict:
    """Content fingerprint of everything a calculation depends on."""
    wp1_dir = Path(wp1_dir)
    config_fp = Path(config_fp)
    inputs = {
        "config": config_fp,
        "gmpe_lt": wp1_dir / _read_key(config_fp, "gsim_logic_tree_file"),
        "ssc_lt": wp1_dir / _read_key(config_fp, "source_model_logic_tree_file"),
        "site_model": wp1_dir / _read_key(config_fp, "site_model_file"),
    }
    # cache_utils hashes a non-existent path as a *string*, which would look like a
    # perfectly valid fingerprint while tracking nothing. A missing input here means
    # the calculation cannot run anyway, so fail loudly instead.
    absent = [f"{k}: {v}" for k, v in inputs.items() if not Path(v).is_file()]
    if absent:
        raise FileNotFoundError(
            f"Cannot fingerprint '{config_fp.name}' - input file(s) missing:\n"
            + "\n".join(f"  - {a}" for a in absent)
        )
    return fingerprint(**inputs, source_models_digest=_source_models_digest(wp1_dir))


def _read_key(config_fp: Path, key: str) -> str:
    """Pull a single ``key = value`` out of a job .ini.

    Deliberately not configparser: the file is only ever read here for the three
    filenames needed to fingerprint it, and a regex avoids depending on the
    engine's own (looser) parsing of the multi-line dict values.
    """
    m = re.search(rf"^{re.escape(key)}\s*=\s*(.+)$", Path(config_fp).read_text(), re.M)
    if not m:
        raise KeyError(f"'{key}' not found in {Path(config_fp).name}")
    return m.group(1).strip()


def _calc_exists(calc_id: int) -> bool:
    """True when the calc_id still resolves to a readable datastore.

    Guards a manifest that outlived its datastore (wiped ~/oqdata, different
    machine), which would otherwise hand downstream code a dead id.
    """
    try:
        from openquake.commonlib.datastore import read

        read(int(calc_id)).close()
        return True
    except Exception:
        return False


def load_manifest(manifest_fp: Path) -> dict:
    """Parsed manifest, or ``{}`` when it does not exist yet."""
    manifest_fp = Path(manifest_fp)
    if not manifest_fp.is_file():
        return {}
    with open(manifest_fp) as f:
        return json.load(f)


def load_calc_ids(manifest_fp: Path) -> dict[str, int]:
    """``{analysis_name: calc_id}`` — the accessor for post-processing."""
    return {k: v["calc_id"] for k, v in load_manifest(manifest_fp).items()}


def _write_manifest_entry(manifest_fp: Path, name: str, entry: dict) -> None:
    manifest_fp = Path(manifest_fp)
    manifest = load_manifest(manifest_fp)
    manifest[name] = entry
    manifest_fp.parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_fp, "w") as f:
        json.dump(manifest, f, indent=2)


# The engine tags every log line with the calc id and finally reports where the
# datastore was written, e.g.
#   [2026-07-17 14:22:42 #11 WARNING] Stored 67.17 MB on ...\calc_11.hdf5 in 177 seconds
# The datastore filename is the most specific signal, so try it first and fall back
# to the "#<id>" log prefix.
_CALC_ID_PATTERNS = (
    re.compile(r"calc_(\d+)\.hdf5"),
    re.compile(r"^\[[\d\-]+ [\d:]+ #(\d+) ", re.M),
)


def _calc_id_from_output(text: str) -> int | None:
    """Scrape the calc_id out of the engine's log output."""
    for pattern in _CALC_ID_PATTERNS:
        ids = pattern.findall(text)
        if ids:
            # Every line of a run carries the same id; take the last in case the
            # log ever contains more than one calculation.
            return int(ids[-1])
    return None


# Invoke the engine through the *current* interpreter rather than a bare "oq" on
# PATH: PATH only has oq.exe when the venv is activated (a plain `.venv/…/python.exe
# script.py` does not), and this also guarantees the calculation runs against the
# same engine the notebook imported.
_OQ_CMD = [sys.executable, "-m", "openquake.commands"]


def _sibling_descriptions(wp1_dir: Path) -> set[str]:
    """Descriptions of every analysis config in ``wp1_dir``.

    Read from disk rather than from a constant so that the ambiguity check below
    always reflects the analyses actually being run — the notebook owns the
    truncation levels, and a hardcoded copy here would go stale the moment an
    analyst changed them.
    """
    descs = set()
    for fp in sorted(Path(wp1_dir).glob("config_*.ini")):
        try:
            descs.add(_read_key(fp, "description"))
        except KeyError:
            continue
    return descs


def _calc_id_from_listing(description: str, wp1_dir: Path) -> int | None:
    """Recover a calc_id by matching the (unique) description in the engine's
    listing. Fallback for when the log output cannot be scraped.

    The listing's ``description`` column is *truncated* to a fixed width, so an
    exact match never fires — compare the shown text as a prefix instead. The
    per-analysis descriptions differ in their ``epsN`` suffix, so verify the
    truncation did not cut off what makes them unique before trusting a match.
    """
    out = subprocess.run(
        [*_OQ_CMD, "engine", "--list-hazard-calculations"],
        capture_output=True, text=True,
    )
    all_descs = _sibling_descriptions(wp1_dir)

    matches = []
    for line in out.stdout.splitlines():
        cols = [c.strip() for c in line.split("|")]
        if len(cols) < 5 or not cols[0].isdigit() or not cols[4]:
            continue
        shown = cols[4]
        if not description.startswith(shown):
            continue
        # The truncated text must still tell this analysis apart from its siblings
        # (they differ only in the trailing 'epsN'), or the id could be the wrong one.
        if sum(1 for d in all_descs if d.startswith(shown)) > 1:
            raise RuntimeError(
                f"Cannot identify the calc_id for '{description}': the calculation "
                f"listing truncates it to '{shown}', which matches more than one "
                f"analysis."
            )
        matches.append(int(cols[0]))
    return max(matches) if matches else None


def _read_log(log_fp: Path) -> str:
    """Decode a log written by PowerShell, whatever encoding it chose.

    Windows PowerShell 5.1's Tee-Object writes UTF-16LE with a BOM (and has no
    -Encoding switch to stop it), while pwsh 7 writes UTF-8. Decoding UTF-16 as
    UTF-8 yields space-separated mojibake that silently matches no regex, so
    dispatch on the BOM rather than assuming.
    """
    if not log_fp.is_file():
        return ""
    raw = log_fp.read_bytes()
    for bom, enc in (
        (b"\xff\xfe", "utf-16"),  # the utf-16/utf-8-sig codecs strip the BOM for us
        (b"\xfe\xff", "utf-16"),
        (b"\xef\xbb\xbf", "utf-8-sig"),
    ):
        if raw.startswith(bom):
            return raw.decode(enc, errors="replace")
    return raw.decode("utf-8", errors="replace")


def _run_in_new_window(config_fp: Path, wp1_dir: Path, log_fp: Path) -> tuple[int, str]:
    """Run the engine in its own console window, teeing output to ``log_fp``.

    A separate console shows the engine's live progress bars, but its output no
    longer comes back down a pipe — so PowerShell's Tee-Object mirrors it to a log
    that the calc_id is then scraped from. ``exit $LASTEXITCODE`` is needed because
    the PowerShell process would otherwise report its *own* exit code, not the
    engine's, and a failed calculation would look like a success.

    Returns ``(returncode, output_text)``.
    """
    log_fp.parent.mkdir(parents=True, exist_ok=True)
    oq = " ".join(f"'{c}'" if " " in str(c) else str(c) for c in _OQ_CMD)
    ps = (
        f"& {oq} engine --run '{config_fp.name}' 2>&1 | "
        f"Tee-Object -FilePath '{log_fp}'; exit $LASTEXITCODE"
    )
    # pwsh (7+) writes UTF-8 logs; Windows PowerShell 5.1 writes UTF-16. Either is
    # handled by _read_log, so fall back to whichever shell exists.
    shell = shutil.which("pwsh") or "powershell"
    proc = subprocess.Popen(
        [shell, "-NoProfile", "-Command", ps],
        cwd=wp1_dir,
        creationflags=subprocess.CREATE_NEW_CONSOLE,
    )
    proc.wait()
    return proc.returncode, _read_log(log_fp)


def run_or_reuse(
    name: str,
    config_fp: Path,
    wp1_dir: Path,
    manifest_fp: Path,
    *,
    force_rerun: bool = False,
    dry_run: bool = False,
    new_window: bool = False,
) -> int | None:
    """Launch a PSHA calculation, or reuse the recorded one when inputs match.

    Unlike :func:`cache_utils.load_or_compute`, changed inputs are *not* an error
    here — re-running is the intended remedy, so a mismatch prints what changed
    and relaunches. Returns the calc_id (``None`` under ``dry_run``).

    With ``new_window`` (Windows only) each calculation opens its own console so
    its progress can be watched; output is still teed to ``wp1_dir/logs/<name>.log``.
    Runs remain sequential either way — the engine parallelises internally, so
    concurrent calculations would only contend for cores.
    """
    config_fp, wp1_dir, manifest_fp = Path(config_fp), Path(wp1_dir), Path(manifest_fp)
    fp_dict = fingerprint_calc(config_fp, wp1_dir)
    entry = load_manifest(manifest_fp).get(name)

    if entry and not force_rerun:
        changes = _diff_inputs(entry.get("inputs", {}), fp_dict)
        if changes and not dry_run:
            print(f"[oq] '{name}' inputs changed since calc_id={entry['calc_id']}:")
            print("\n".join(changes))
        elif changes:
            print(f"[oq] '{name}' inputs changed - would re-run (dry_run).")
            return None
        elif not _calc_exists(entry["calc_id"]):
            print(f"[oq] '{name}' calc_id={entry['calc_id']} no longer in the datastore; re-running.")
        else:
            print(f"[oq] '{name}' reusing calc_id={entry['calc_id']} (inputs match).")
            return entry["calc_id"]

    if dry_run:
        print(f"[oq] '{name}' would run {config_fp.name} (dry_run).")
        return None

    desc = _read_key(config_fp, "description")
    log_fp = wp1_dir / "logs" / f"{name}.log"
    # cwd matters: every path inside the .ini is relative to the config's folder.
    if new_window and sys.platform == "win32":
        print(f"[oq] '{name}' running {config_fp.name} in a new window "
              f"(log: {log_fp.relative_to(wp1_dir)}) ...")
        returncode, text = _run_in_new_window(config_fp, wp1_dir, log_fp)
    else:
        if new_window:
            print(f"[oq] new_window is Windows-only (platform={sys.platform}); "
                  f"running inline.")
        print(f"[oq] '{name}' running {config_fp.name} ...")
        proc = subprocess.run(
            [*_OQ_CMD, "engine", "--run", config_fp.name],
            cwd=wp1_dir, capture_output=True, text=True,
        )
        returncode, text = proc.returncode, proc.stdout + proc.stderr

    if returncode != 0:
        raise RuntimeError(
            f"'oq engine --run {config_fp.name}' failed (exit {returncode}):\n"
            f"{text[-4000:]}"
        )

    calc_id = _calc_id_from_output(text) or _calc_id_from_listing(desc, wp1_dir)
    if calc_id is None:
        raise RuntimeError(
            f"'{name}' ran but no calc_id could be recovered from the engine output "
            f"or the calculation listing. Last output:\n{text[-2000:]}"
        )

    _write_manifest_entry(manifest_fp, name, {
        "calc_id": calc_id,
        "config": config_fp.name,
        "description": desc,
        "inputs": fp_dict,
        "_meta": {
            "git_commit": _git_commit(),
            "written_at": datetime.now(timezone.utc).isoformat(),
        },
    })
    print(f"[oq] '{name}' completed: calc_id={calc_id}")
    return calc_id
