# This model uses all 21 branches of the site model but only a single median
# branch for each GMPE for all the sites selected for this study.
# The IM is AvgSA[0,6] wiht 10 evenly spaced periods
# Dissagregation is carried out for 5 poes ranging from 1/50 to 1/4475 yr

[general]
description = [ESHM20 AvgSA 0 to 6 - all sites]
calculation_mode = disaggregation
random_seed = 23

[geometry]

[logic_tree]

[erf]
rupture_mesh_spacing = 5
complex_fault_mesh_spacing = 50
width_of_mfd_bin = 0.1
area_source_discretization = 10.0
pointsource_distance = 75
ps_grid_spacing = 50

[site_params]
reference_vs30_type = measured
reference_vs30_value = 800.0
site_model_file = site_model_all_sites.csv

reference_depth_to_1pt0km_per_sec = 30.0

[calculation]
source_model_logic_tree_file = source_model_logic_tree_eshm20.xml
gsim_logic_tree_file = gmpe_logic_tree_AvgSA_0to6_median_branch.xml

investigation_time = 1.0

intensity_measure_types_and_levels = {"AvgSA": logscale(0.0005, 3.00, 25)}

truncation_level = 3
maximum_distance = {'Craton': 400.0,
                    'Subduction Interface': 250.0,
                    'Subduction Inslab': 300.0,
                    'Non-Subduction Deep':500.0,
                    'Volcanic':50.0,
                    'default': 200.0}

[disaggregation]
disagg_outputs = TRT_Mag_Dist_Eps
max_sites_disagg = 60
poes_disagg = 0.02 0.0021030 0.000667 0.000404 0.000201
mag_bin_width = 0.5
distance_bin_width = 20.0
coordinate_bin_width = 5
num_epsilon_bins = 6

