# References and Citation
# Please use this citation when the OpenQuake input files are used:
# Danciu ,et al (2021) - https://doi.org/10.12686/a15
# contact:
# laurentiu.danciu[at]sed.ethz.ch
[general]
description = [ESHM20 v12e main region - investigation_time=1yr ]
calculation_mode = classical
random_seed = 23

[geometry]

[logic_tree]

[erf]
rupture_mesh_spacing = 5
complex_fault_mesh_spacing = 50
width_of_mfd_bin = 0.1
area_source_discretization = 10.0

pointsource_distance = 75
ps_grid_spacing = 50

[site_params]
reference_vs30_type = measured
reference_vs30_value = 800.0
site_model_file = site_model_casestudy_sites.csv

reference_depth_to_1pt0km_per_sec = 30.0

[calculation]
source_model_logic_tree_file = source_model_logic_tree_eshm20.xml
gsim_logic_tree_file = gmpe_logic_tree_SA_median_branch.xml

investigation_time = 1.0

intensity_measure_types_and_levels = {"PGA": logscale(0.0005, 5.00, 25),
                                      "SA(0.05)": logscale(0.0005, 5.00, 25),
                                      "SA(0.10)": logscale(0.0005, 5.00, 25),
                                      "SA(0.15)": logscale(0.0005, 5.00, 25),
                                      "SA(0.20)": logscale(0.0005, 5.00, 25),
                                      "SA(0.25)": logscale(0.0005, 5.00, 25),
                                      "SA(0.30)": logscale(0.0005, 5.00, 25),
                                      "SA(0.35)": logscale(0.0005, 5.00, 25),
                                      "SA(0.40)": logscale(0.0005, 5.00, 25),
                                      "SA(0.45)": logscale(0.0005, 5.00, 25),
                                      "SA(0.50)": logscale(0.0005, 5.00, 25),
                                      "SA(0.55)": logscale(0.0005, 5.00, 25),
                                      "SA(0.60)": logscale(0.0005, 5.00, 25),
                                      "SA(0.65)": logscale(0.0005, 5.00, 25),
                                      "SA(0.70)": logscale(0.0005, 5.00, 25),
                                      "SA(0.75)": logscale(0.0005, 5.00, 25),
                                      "SA(0.80)": logscale(0.0005, 5.00, 25),
                                      "SA(0.85)": logscale(0.0005, 5.00, 25),
                                      "SA(0.90)": logscale(0.0005, 5.00, 25),
                                      "SA(0.95)": logscale(0.0005, 5.00, 25),
                                      "SA(1.00)": logscale(0.0005, 5.00, 25),
                                      "SA(1.05)": logscale(0.0005, 5.00, 25),
                                      "SA(1.10)": logscale(0.0005, 5.00, 25),
                                      "SA(1.15)": logscale(0.0005, 5.00, 25),
                                      "SA(1.20)": logscale(0.0005, 5.00, 25)}

truncation_level = 4
maximum_distance = {'Craton': 400.0,
                     'Subduction Interface': 250.0,
                     'Subduction Inslab': 300.0,
                     'Non-Subduction Deep':500.0,
                     'Volcanic':50.0,
                     'default': 200.0}

[output]
export_dir = output/
mean_hazard_curves = true
hazard_maps = true
quantile_hazard_curves = 0.16 0.50 0.84
poes = 0.019801 0.004988 0.002103 0.001000 0.000404 0.000201 0.000100
